version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    # Only add depends_on if frontend is actually needed for backend to start
    # depends_on:
    #   - frontend
    # Typically you'd want to add restart policy for production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped