version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "globalPaymentsPlatform/backend/package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies in Backend
          command: cd globalPaymentsPlatform/backend && npm install
      - run:
          name: Update Deprecated Packages
          command: |
            cd globalPaymentsPlatform/backend
            npm update inflight glob
      - run:
          name: Connect to MongoDB Atlas
          command: |
            cd globalPaymentsPlatform/backend
            MONGO_URI=$(echo $MONGODB_URI | sed 's/test/test-ci/')
            export MONGO_URI
      - run:
          name: Seed Test Data (if needed)
          command: |
            cd globalPaymentsPlatform/backend
            node seed-data.js
      - save_cache:
          paths:
            - globalPaymentsPlatform/backend/node_modules
          key: v1-dependencies-{{ checksum "globalPaymentsPlatform/backend/package-lock.json" }}
      - run:
          name: Run Tests
          command: |
            cd globalPaymentsPlatform/backend
            npm test -- --detectOpenHandles

  # New job to build Docker images without pushing
  build_images:
    docker:
      - image: docker:24.0.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Backend Image
          command: |
            cd globalPaymentsPlatform/backend
            docker build -t st10067544/globalpayments-backend:test .
      - run:
          name: Build Frontend Image
          command: |
            cd globalPaymentsPlatform/frontend
            docker build -t st10067544/globalpayments-frontend:test .

  # Modified build_and_push job that only runs on main
  build_and_push:
    docker:
      - image: docker:24.0.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build and Push Backend
          command: |
            cd globalPaymentsPlatform/backend
            docker build -t st10067544/globalpayments-backend:latest .
            docker push st10067544/globalpayments-backend:latest
      - run:
          name: Build and Push Frontend
          command: |
            cd globalPaymentsPlatform/frontend
            docker build -t st10067544/globalpayments-frontend:latest .
            docker push st10067544/globalpayments-frontend:latest

workflows:
  test_and_deploy:
    jobs:
      - test
      - build_images:
          requires:
            - test
      - build_and_push:
          requires:
            - build_images
          filters:
            branches:
              only:
                - main