version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.20.0 # Updated image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "globalPaymentsPlatform/backend/package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies in Backend
          command: cd globalPaymentsPlatform/backend && npm install
      - run:
          name: Update Deprecated Packages
          command: |
            cd globalPaymentsPlatform/backend
            npm update inflight glob
      - run:
          name: Connect to MongoDB Atlas
          command: |
            cd globalPaymentsPlatform/backend
            MONGO_URI=$(echo $MONGODB_URI | sed 's/test/test-ci/')
            export MONGO_URI
      - run:
          name: Seed Test Data (if needed)
          command: |
            cd globalPaymentsPlatform/backend
            node seed-data.js
      - save_cache:
          paths:
            - globalPaymentsPlatform/backend/node_modules
          key: v1-dependencies-{{ checksum "globalPaymentsPlatform/backend/package-lock.json" }}
      - run:
          name: Run Tests
          command: |
            cd globalPaymentsPlatform/backend
            npm test -- --detectOpenHandles

workflows:
  test:
    jobs:
      - test
